MEMORY
{
  ROM (rx): ORIGIN = 0, LENGTH = 1M
  RAM (wxa) : ORIGIN = 1M, LENGTH = 4095M
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
